# Generated by Django 5.2 on 2025-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonregistro",
            name="comentarios",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonregistro",
            name="genero",
            field=models.CharField(
                choices=[
                    ("desconocido", "Desconocido"),
                    ("masculino", "Masculino"),
                    ("femenino", "Femenino"),
                ],
                default="desconocido",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="pokemonregistro",
            name="naturaleza",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pokemonregistro",
            name="nivel",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pokemonregistro",
            name="shiny",
            field=models.BooleanField(default=False),
        ),
    ]
